site_name: FlowGraph Documentation
site_description: A modern, HTML-based visual scripting library for creating interactive node-based graphs
site_author: FlowGraph Team
site_url: https://sps014.github.io/visual-flow-graph

# Repository
repo_name: sps014/visual-flow-graph
repo_url: https://github.com/sps014/visual-flow-graph
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for automatic mode switching
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.remember
    - navigation.instant.rewrite
    - navigation.instant.tracking
    - navigation.instant.worker
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye


# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: flowgraph
      repo: flowgraph
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Installation: installation.md
  - Basic Examples: basic-examples.md
  - Components:
    - flow-graph.md
    - flow-node-def.md
    - flow-socket.md
    - flow-edge.md
    - flow-context-menu.md
  - API Reference:
    - api/flowgraph.md
    - api/events.md
    - api/execution.md
    - api/animations.md
  - Customization:
    - theming.md
    - styling.md
    - custom-nodes.md
    - custom-sockets.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sps014/visual-flow-graph
  version:
    provider: mike

# Copyright
copyright: Copyright &copy; 2024 FlowGraph Team - <a href="https://github.com/sps014/visual-flow-graph">GitHub</a>
